= txtconv4mv

image:https://travis-ci.org/jiro4989/txtconv4mv.svg?branch=master["Build Status", link="https://travis-ci.org/jiro4989/txtconv4mv"]

Excelとかで作ったCSVファイルをRPGツクールMVのテキストデータに変換するツール。

== 目指すところ

一番最初、ゲーム内のイベントとか画像の細かい調整などについては
ツクール側でやってもらうにして、一番最初の膨大なテキストデータ、シナリオの作成を
外部のエディタ（ExcelやLibreOffice）で行い、ツクールに取り込むところまでを行う。
その後、イベント内に埋め込む作業はツクール内で行う。

== 使い方

* Excelを開く
* 編集する
* CSVとして保存する
* このツールを起動する
* ツクールのプロジェクトを指定する
* ツクールを起動する

=== コマンドライン

[source,bash]
----
$ txtconv4mv config init
# ツクールのプロジェクトディレクトリとかもろもろをここで設定

$ ls config/
Game1.json
# プロジェクトの名前が設定ファイルの名前になる

$ txtconv4mv convert config/Game1.json
# プロジェクトに変換されたデータが追加される

$ ls $HOME/Documents/Game/Game1/data/Map*.json
Map001.json MapInfo.json

$ ls backup/yyyy-mm-dd
Map001.json MapInfo.json
----

== できること

* CSVをツクールMVのデータに変換
* 変換時のデータ整合性チェック
** データに不正があった場合はどこに不正があったのかを表示
* ツクールMVのプロジェクトからテキストデータのみの抽出
** ただし抽出のみのため、もとのデータの完全再現は不可能
* データ埋め込み前のバックアップ
** 万が一データが破損した際は復元できるようにする
* ツクールへのデータ変換の際にインデント、括弧でくくる、テキストを折り返す、次の
  テキストに移すなどをオプションで行う。
** 設定ファイルが存在したときにその設定をもとにデータ変換を行う
** データ変換設定は対話式の画面から選択してJSONファイルを生成する
* 問題が見つかった際には調査ができるようにログを記録する
* 括弧でくくる際はconfig.jsonから選択できるようにする
